
= ChartSeries.vba
:experimental:
:icons:         // not sure if this is needed
:sourcedir: ../src
:testdir: ../tests
:uri-commit-messages: https://www.conventionalcommits.org
:uri-GitHub-FirstContribution: https://github.com/firstcontributions/first-contributions
:uri-license: https://choosealicense.com/licenses/mit/
:uri-rubberduck: https://rubberduckvba.com/
:uri-UnitTests: https://en.wikipedia.org/wiki/Unit_testing
// show the corresponding icons on GitHub, because otherwise "just" the text will be shown
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :information_source:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

Excel VBA class to get Chart Series data.

The original version was created by John Walkenbach a loooong time ago.
Actually, it is that old that I can't remember _when_ I have found it.
The only thing that is sure is, that it must have been between 1999 and 2014.
Many thanks for that and his allowance to publish it although in the meantime it is very likely that not a single line of the original code is left.

== Features

* extends the Excel `Series` class
* progress any `Series` formula that is accessible, i.e. shows up in the formula bar
* extract the series formula parts (name, x values, y values, plot order and, if present, the bubble size)
* extract the series formula parts as string or range (if it is a range)
* should work also for the "`hard`" stuff, e.g.
** series names containing double quotes
** workbook or worksheet names that contain spaces, single quotes, double quotes
** multi-area ranges

[#prerequisites]
== Prerequisites / Dependencies

Since this is an Excel VBA class/module you obviously need Microsoft Excel.

[#how-to-install]
== How to install / Getting started

Add the CLS and BAS files from the link:{sourcedir}[src] folder to your project.

._If you need some more advice on how to do that, expand me._
[%collapsible]
====
. Open Microsoft Excel.
. Open the Visual Basic Editor (VBE) (kbd:[Alt+F11]).
. Add the file(s) in the link:{sourcedir}[src] folder to your VBA project.
** With {uri-rubberduck}[Rubberduck]:
.. Right-click on the project to which you want to add the file(s) in the "`Code Explorer`" (to show it press kbd:[Ctrl+R]) and click on menu:Add[Existing Files...].
.. Select all files in the link:{sourcedir}[src] folder and click on btn:[Open].
** Without Rubberduck:
.. Select all files in the link:{sourcedir}[src] folder in Windows File Explorer.
.. Drag-and-drop them to the corresponding project in VBE's "`Project Explorer`". +
   (To show it press kbd:[Ctrl+R].
   Hit it twice if the Code Explorer shows up first.)
// BUG: "project name" can't be put in normal angle brackets, because the closing bracket would be interpreted as menu delimiter. I couldn't find a way how to "escape" that (i.e. a backslash didn't work). Thus, single guillemets are used.
. Check, if there are obvious errors by compiling the project (menu:Debug[Compile ‹project name›]).
. Save the file/project.
.. Be sure that the file/project you want to save is "`active`" in the VBE by checking, if its name is shown in VBE's title bar. +
   (If it's not, open a (class) module of the corresponding project (and close it again).)
.. Press the "`Save`" button (the disc symbol similar to 💾) in VBE's toolbar.
.. Check that the file (really) was saved by having a look at the "`last modified date`" of the (project) file in the Windows File Explorer.
====

== Usage / Show it in action

Imagine you have the (valid) series formula

[source]
----
=SERIES("name: !'""b),",(',(''a"''!'!$A$4,',(''a"''!'!$A$5:$A$6,',(''a"''!'!$A$7),(',(''a"''!'!$C$4,',(''a"''!'!$C$5:$C$6,',(''a"''!'!$C$7),2)
----

I guess even _you_ would need a while to figure out where the individual formula parts start and end, right?
With this class you can easily identify them.
For example the code

[source,vba]
----
Sub ExampleUsage()
    Dim srs As Series
    Set srs = ActiveChart.FullSeriesCollection(2)

    Dim MySeries As IChartSeries
    Set MySeries = ChartSeries.Create(srs)
    With MySeries
        If Not .IsSeriesAccessible Then Exit Sub

        Debug.Print "FullFormula:        " & .FullFormula

        With .SeriesName
            Debug.Print "SeriesName:"
            If .EntryType = eEntryType.eRange Then
                Debug.Print "  RangeString:      " & .RangeString
            Else
                Debug.Print "  FormulaPart:      " & .FormulaPart
                Debug.Print "  CleanFormulaPart: " & .CleanFormulaPart
            End If
        End With

        With .XValues
            Debug.Print "XValues:"
            If .EntryType = eEntryType.eRange Then
                Debug.Print "  RangePath:        " & .RangePath
                Debug.Print "  RangeBook:        " & .RangeBook
                Debug.Print "  RangeSheet:       " & .RangeSheet
                Debug.Print "  RangeString:      " & .RangeString
            Else
                Debug.Print "  CleanFormulaPart: " & .CleanFormulaPart
            End If
        End With

        With .PlotOrder
            Debug.Print "PlotOrder:"
            Debug.Print "  Value:            " & .Value
        End With
    End With
End Sub
----

will write

[source]
----
FullFormula:        =SERIES("name: !'""b),",(',(''a"''!'!$A$4,',(''a"''!'!$A$5:$A$6,',(''a"''!'!$A$7),(',(''a"''!'!$B$4,',(''a"''!'!$B$5:$B$6,',(''a"''!'!$B$7),2)
SeriesName:
  FormulaPart:      "name: !'""b),"
  CleanFormulaPart: name: !'"b),
XValues:
  RangePath:
  RangeBook:        DummyWorkbook.xlsx
  RangeSheet:       ,('a"'!
  RangeString:      A4,A5:A6,A7
PlotOrder:
  Value:            2
----

to VBE's Immediate Window.
(I leave it up to you as an exercise to find out how to get the y values.)
Thus,

* the series name is given as string with the value `name: !'"b),`,
* the x data come from range `A4,A5:A6,A7` on sheet `,('a"'!`,
* the y data come from range `C4,C5:C6,C7` on sheet `,('a"'!`, and
* the (total) plot order is `2`.


== Running Tests

Yes, {uri-UnitTests}[Unit Tests] in Excel _are_ possible.
For that you need to have the awesome {uri-rubberduck}[Rubberduck] AddIn installed (and enabled).

The procedure is very similar to the one given in the <<how-to-install>> section, but this time add the files from the link:{testdir}[tests] folder (instead of the files from the link:{sourcedir}[src] folder).
When you are done with that, additionally perform the following steps.

. Check that the files from the link:{sourcedir}[src] folder are present in the project as well or that you have a reference to project with the source files.footnote:[
   See the collapsible in the next point on how to do that.
   If you use the Rubberduck way, before adding the reference you first need to switch to the menu:Projects[] tab.
] +
  (Otherwise tests will/should fail.)
. Add a reference to the "`Rubberduck AddIn`" to the project (with the test modules).
+
._If you don't have a clue how to do that, expand me._
[%collapsible]
====
* With {uri-rubberduck}[Rubberduck]:
. Right-click somewhere on the project in the "`Code Explorer`" and click on menu:Add/Remove{sp}References...[].
. Add the reference.
.. Type (parts of) the library name in the search box until you see it in below (left) list or it is empty.
** If the AddIn file name is in the lower left list box:
... Select the library in the (left) list and
... click on the btn:[➨] button to add it to the project references. +
** If the the AddIn file name is _not_ in the list:
... Click on the btn:[Browse...] button.
... Browse to the folder where the AddIn is located.
... Select the AddIn and
... press the btn:[Open] button.
. Click on the btn:[OK] button to close the window.
* Without Rubberduck:
. Open the Reference manager in the VBE (menu:Tools[References...]).
** If the AddIn project name is in the list of available references:
.. Add a checkmark to the corresponding library.
** If it's _not_ in the list:
.. Click on the btn:[Browse...] button.
.. Browse to the folder where the AddIn is located.
.. Select the AddIn and
.. press the btn:[Open] button.
. Click on the btn:[OK] button to close the window.
. Save the file/project.
====
+
. Open the "`Test Explorer`" (menu:Rubberduck[Unit Tests > Test Explorer]).
. Run the tests by clicking menu:Run[All Tests].

Because not all the test series (and corresponding data) can be created via code you will find them in the Excel files in the link:{testdir}[tests] folder.

[#used-by]
== Used By

This project is used by (at least) these projects:

* https://github.com/VBA-tools2/SeriesEntriesInCharts.vba[]

If you know more, we will be happy to add them here.

== Known issues and limitations

I almost exclusively work with scatter charts.
So I am not sure if the `ChartSeries` class also (fully) works for other chart/series types.

[#contributing]
== Contributing

All contributions are highly welcome!!

If you are new to git/GitHub, please have a look at {uri-GitHub-FirstContribution} where you will find a lot of useful information for beginners.

I recently was pointed to {uri-commit-messages} which sounds very promising.
I'll use them from now on too (and hopefully don't forget it in a hurry).

== FAQ

[qanda]
What are the `+'@...+` comments good for in the code?::
You should really have a look at the awesome {uri-rubberduck}[Rubberduck] project!

== License

{uri-license}[MIT]
